### ISSUE TITLE
Recently played section

### ISSUE THREAD

**Issue by 42Willow** [tthn0/Spotify-Readme#11]

**Comment by tthn0** [comment]
Hi, can you please describe the issue you're having?

**Comment by 42Willow** [comment]
No issues, just a suggestion for another feature. Similar to this but matching the design: https://github.com/JeffreyCA/spotify-recently-played-readme

Don't worry about it if you can't be bothered or don't think it should be added.

**Comment by 42Willow** [comment]
Actually dw about this I'll see if I can change the colours of the other one 👍
