### ISSUE TITLE
404 error when deploying

### ISSUE THREAD

**Issue by swersk** [tthn0/Spotify-Readme#12]
<img width="498" alt="Screenshot 2023-08-14 at 1 16 48 PM" src="https://github.com/tthn0/Spotify-Readme/assets/111617376/464e834a-a3d5-4ef2-8ae4-66dd1d12b7bc">

After deploying on Vercel I see this error. 

I tried revising my vercel.json to be this:
 
 
```
{
  "rewrites": [
    { "source": "/(.*)", "destination": "/" }
  ],
  "headers": [
    {
      "source": "/api/(.*)",
      "headers": [
        { "key": "Access-Control-Allow-Credentials", "value": "true" },
        { "key": "Access-Control-Allow-Origin", "value": "*" },
        { "key": "Access-Control-Allow-Methods", "value": "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
        { "key": "Access-Control-Allow-Headers", "value": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" }
      ]
    }
  ]
}
 
```

That didn't work. 

Any tips are greatly appreciated.

**Comment by tthn0** [comment]
Hi, there is no need to modify your `vercel.json` file. You just need to visit `https://{PROJECT_NAME}.vercel.app/api`, replacing `{PROJECT_NAME}` with the name you gave your Vercel project.

Please check your the logs for your Vercel project and reply with a screenshot of the error you're getting

**Comment by nyas1** [comment]
![image](https://github.com/tthn0/Spotify-Readme/assets/85426900/a0496883-352c-44be-a0b3-f9a3f4c4476c)
the same is happening with me, i did not change any files and thoroughly followed all steps but still its not working...
