### ISSUE TITLE
Deployment Issue "This Serverless Function has crashed"

### ISSUE THREAD

**Issue by IndraTensei** [tthn0/Spotify-Readme#17]
![image](https://github.com/tthn0/Spotify-Readme/assets/69427966/c808c73c-04b5-4041-ad11-5777ec173ef9)

The log
![image](https://github.com/tthn0/Spotify-Readme/assets/69427966/5af69c78-4a17-4dc8-8db9-36cb37d39fc3)

**Comment by IndraTensei** [comment]
Found the fix in this [stackoverflow ](https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls) thread.
it seems  Werkzeug 3.0.0 was released and Flask doesn't specify the dependency correctly (requirements says Werkzeug>=2.2.0). This is why, Werkzeug 3.0.0 is still installed and Flask 2.2.2 isn't made for Werkzeug 3.0.0.

Solution: Just set a fix version for Werkzeug such as Werkzeug==2.2.2 in your requirements.txt and it should work.

**Comment by IndraTensei** [comment]
#18

**Comment by IndraTensei** [comment]
#18 Made a pull request to fix the above issue

**Comment by ErickDaniel7** [comment]
Thx man
