### ISSUE TITLE
Deployment Error: 404: NOT_FOUND and ImportModuleError: Unable to import module 'vc__handler__python

### ISSUE THREAD

**Issue by LSierra1** [tthn0/Spotify-Readme#19]
"I followed all the steps successfully, but after deploying, it's throwing an error. In the preview, I'm getting a 404: NOT_FOUND with the code: NOT_FOUND, and in the logs, there's a 500 [ERROR] with the message 'Runtime.ImportModuleError: Unable to import module 'vc__handler__python': cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py)'."

![image](https://github.com/tthn0/Spotify-Readme/assets/96590298/a55e996f-9b68-4cde-9f71-3af64804bf3c)

**Comment by tribhuwan-kumar** [comment]
The error you're encountering is due to the `url_quote` function has been moved from `werkzeug.urls` to `werkzeug.utils` in recent versions of the Werkzeug library. So you need to upgrade the `flask` to its latest version `3.0.0`. I've just fixed this error

**Comment by LSierra1** [comment]
Yeah, this solved my problem. Thanks a lot <3
