### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Zemerik** [tthn0/Spotify-Readme#26]
Hey, the images that you provided in the README.md file are not loading. Can you please fix this issue so that users can see a preview of each Widget

![image](https://github.com/tthn0/Spotify-Readme/assets/133865660/fe7e7942-06fc-4527-a102-b60eb664f628)

Regards, 
Zemerik

**Comment by tthn0** [comment]
Working on a fix rn!

**Comment by Zemerik** [comment]
👍
