### ISSUE TITLE
ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by Nazchanel** [tthn0/Spotify-Readme#32]
I followed all the instructions maybe I missed something but I'm getting this

![Screenshot_20240924_230759](https://github.com/user-attachments/assets/267f8978-f9bf-40f6-a8f1-598f96722eb3)

after looking at the logs I found that error is 

```
2024-09-25 03:03:11,749: Error running WSGI application
2024-09-25 03:03:11,751: ModuleNotFoundError: No module named 'main'
2024-09-25 03:03:11,751: File "/var/www/nazchanel_pythonanywhere_com_wsgi.py", line 124, in <module>
2024-09-25 03:03:11,751: from main import app as application
```

Please tell me how to fix this or if this is a bug.

**Comment by krey-yon** [comment]
@Nazchanel i am getting same issue

**Comment by krey-yon** [comment]
@Nazchanel i found the problem you prbly didnt followed the steps correctly. go to wsgi config file and then 
edit ```path = '/home/{PA_USERNAME}/Spotify-Readme/Source'``` use your PA username

**Comment by Nazchanel** [comment]
```python

import sys

path = '/home/nazchanel/spotify-readme-flask/Source'
if path not in sys.path:
    sys.path.append(path)

from main import app as application
```

this is the line I have in my WSGI file. It's the correct directory

**Comment by SahooShuvranshu** [comment]
> I honestly don't know what I did to fix it but yea the problem was somewhere there. I got the same error and then didn't really do anything and it got fixed. Quite odd but I'm happy.

Can you please share it I am having same issue main function is loading or can able to find even after checking 2 to 5 times still same error

**Comment by SahooShuvranshu** [comment]
> I honestly don't know what I did to fix it but yea the problem was somewhere there. I got the same error and then didn't really do anything and it got fixed. Quite odd but I'm happy.

Well i have mode something amd remade this in vercel check it out: https://github.com/SahooShuvranshu/Spotify-Live-Banner
