### ISSUE TITLE
Vercel functions crash

### ISSUE THREAD

**Issue by A-DBN** [tthn0/Spotify-Readme#4]
Hi, I deployed the repo on vercel and when i'm going on the endpoint /api i get this error

![image](https://user-images.githubusercontent.com/54556960/162596845-011e7ec3-41e7-42b2-9ccd-13f1d1625fc9.png)
![image](https://user-images.githubusercontent.com/54556960/162596848-898fa9ec-5bb9-4494-997d-7ec6eeef6ccc.png)

**Comment by itstommi** [comment]
I am not sure how to fix this error. Can you provide more details on what you did?

**Comment by PrajjuS** [comment]
> Hi, I deployed the repo on vercel and when i'm going on the endpoint /api i get this error
> 
> ![image](https://user-images.githubusercontent.com/54556960/162596845-011e7ec3-41e7-42b2-9ccd-13f1d1625fc9.png) ![image](https://user-images.githubusercontent.com/54556960/162596848-898fa9ec-5bb9-4494-997d-7ec6eeef6ccc.png)

https://github.com/itstommi/Spotify-Readme/issues/6#issuecomment-1114554403
