### ISSUE TITLE
Vercel deployment error

### ISSUE THREAD

**Issue by nqbill** [tthn0/Spotify-Readme#6]
**In my function log vercel**

![image](https://user-images.githubusercontent.com/98865315/165153495-1aa6f4ba-c69d-42ef-a444-266696a2f7b8.png)

and when i visit my url with `/api` [myspotify-nqbill.vercel.app](https://myspotify-nqbill.vercel.app/api)

![image](https://user-images.githubusercontent.com/98865315/165154111-3d5dda2e-a514-42ec-87a8-d782c88c2a84.png)

please help @itstommi

**Comment by PrajjuS** [comment]
Well even I faced the same issue.
The issue is due to upgrade in MarkupSafe:2.1.0 where they have removed soft_unicode.
Release note: https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

Try adding `MarkupSafe==2.0.1` in api/requirements.txt
This will fix that issue
